### PR TITLE
Add support for Oracle

### PR DESCRIPTION
**Pull request by holyjak**
Work in progress - add support for the Oracle database.

### CODE REVIEW

**Comment by holyjak** [comment]
Currently fails to compile due to:

```
Error: Incompatible change of initialization policy for java.lang.Math$RandomNumberGeneratorHolder: trying to change RUN_TIME from the command line to RERUN for random number generator
com.oracle.svm.core.util.UserError$UserException: Incompatible change of initialization policy for java.lang.Math$RandomNumberGeneratorHolder: trying to change RUN_TIME from the command line to RERUN for random number generator
```

**Comment by borkdude** [comment]
@holyjak The xcode version for mac should be bumped to 12.0.0 in the .circleci/config.edn

**Comment by holyjak** [comment]
OK, upgrade of GraalVM fixed the issue above. But I have a new problem: the `io.helidon.integrations.db/ojdbc` wrapper I leverage uses ojdbc10, i.e. only works with java 10+ and there is no version from java 8 I assume. So either I can pack ojdbc8 myself and try to rip out and reuse the reflections description from the helidon package or I have to wait until we can upgrade the sql pod to java11.

**Comment by borkdude** [comment]
@holyjak We can bump the GraalVM to 11 for all except hsqldb using some variable in the script.

**Pull request merged**
