### PR TITLE
Added static build config to .circleci/config.yml

### PR DESCRIPTION
**Pull request by eccentric-j**
- Updates compile script to support BABASHKA_XMX and BABASHKA_STATIC flags
- Adds a -static build for hgsql, postgresql, and oracle to the .circleci/config.yml file

## Outstanding Questions:

1. Is any more work needed than this?
2. How do we test these changes?

### CODE REVIEW

**Comment by borkdude** [comment]
@eccentric-j As discussed on Slack:

> We generate a CircleCI config here: https://github.com/babashka/babashka-sql-pods/blob/master/script/generate_circleci.clj
You would just have to add one extra job that is the same as the other linux one but with the --static, which you could do using an environment variable

So instead of editing the yaml file directly, please make only changes to the generation script.

**Comment by eccentric-j** [comment]
> @eccentric-j As discussed on Slack:
> 
> > We generate a CircleCI config here: https://github.com/babashka/babashka-sql-pods/blob/master/script/generate_circleci.clj
> > You would just have to add one extra job that is the same as the other linux one but with the --static, which you could do using an environment variable
> 
> So instead of editing the yaml file directly, please make only changes to the generation script.

🤦 I can't believe I missed your very clear instructions! Likely too excited after getting everything working + late night I got a little carless. I apologize for that, and it's updated now generated from the script.

However it appears the oracle-linux-static build failed for some reason. Should we try restarting that job to see if it happens again? I am unable to restart it from my end.

https://app.circleci.com/pipelines/github/babashka/babashka-sql-pods/115/workflows/19585d1b-0cbe-43ed-bb23-4d7f03027c6f/jobs/406

**Comment by borkdude** [comment]
@eccentric-j No worries. I think the oracle one needs jvm 11 but somehow it's using java8 in the static build.

**Comment by borkdude** [comment]
@eccentric-j I think only the hsqldb one needs java 8, to be specific.

**Comment by eccentric-j** [comment]
Looks like it worked! Thanks again for reviewing it.

**Pull request merged**
