### PR TITLE
Add builds for linux-aarch64, remove dynamic linux builds

### PR DESCRIPTION
**Pull request by lispyclouds**
Addresses #55

### CODE REVIEW

**Comment by lispyclouds** [comment]
ah forgot to generate

**Comment by lispyclouds** [comment]
@borkdude any recommendations for this?

**Comment by borkdude** [comment]
@lispyclouds Can you describe what is the problem and how you got there?

**Comment by lispyclouds** [comment]
So the versions of the embedded postgres and maria db we use to test arent compatible on linux/arm64. To get around it i updated them to latest, the postgres one says it should have support for arm. Now it seems they need a docker env and it wants to launch a postres container. Additionally the 1.0.0 release of embedded postgres has some changes in the way we configure it too. The MariaDB one still doesnt support ARM i think.

**Comment by borkdude** [comment]
@lispyclouds We can skip tests for arm, as long as the binary builds we can assume it works, as long as the tests for the other platforms pass.

**Comment by lispyclouds** [comment]
Looks good to me now @borkdude

**Pull request merged**
