### PR TITLE
Add in missing relative path

### PR DESCRIPTION
**Pull request by dharrigan**

### CODE REVIEW

**Comment by borkdude** [comment]
@dharrigan These pods can also be installed with brew so then they are on your path and not in your local directory per se.

**Comment by dharrigan** [comment]
Hi,

Very true, although I was failing to run the example, after downloading the pod, as it wasn't clear that if that is done, it's a relative path. Not everyone uses brew :-) I wanted to download the pod to try out the example.

**Comment by borkdude** [comment]
OK, maybe a comment to clarify this will be the correct way of handling it?

**Comment by dharrigan** [comment]
Yes. I can do that if you wish :-)

**Comment by borkdude** [comment]
OK, PR change welcome 👍

**Comment by dharrigan** [comment]
Wording improved :)

**Pull request merged**
